import Head from 'next/head';
import { ListItem } from '../types';
import ItemsLayout from './itemsLayout';

type Props = {
  items: ListItem[]
}

export const getServerSideProps = async (context: {
  query: string;
}) => {
  const response = await fetch(`https://api.punkapi.com/v2/beers`);
  const data = await response.json();
  return {
    props: {
      items: data
    }
  }
}

export default function Home({items}: Props) {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ItemsLayout>
            <div></div>
        </ItemsLayout>
      </main>
    </>
  )
}

