import Head from 'next/head';
import Search from '../components/search';
import Result from '../components/results';
import { ListItem } from '../types';

type Props = {
  items: ListItem[]
}

export async function getServerSideProps() {
  const response = await fetch('https://api.punkapi.com/v2/beers');
  const data = await response.json();

  return {
    props: {
      items: data
    }
  }
}

export default function Home({items}: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Search/>
        <Result items={items}/>
      </main>
    </>
  )
}
